micronaut.application.name=company

datasources.default.url=jdbc:postgresql://localhost:5432/postgres
datasources.default.driver-class-name=org.postgresql.Driver
datasources.default.username=${DB_USERNAME:postgres}
datasources.default.password=${DB_PASSWORD:postgres}
datasources.default.dialect=POSTGRES
datasources.default.connection-init-sql=CREATE SCHEMA IF NOT EXISTS company

liquibase.datasources.default.change-log=classpath:db/changelog/db.changelog-master.xml
liquibase.datasources.default.default-schema=company
liquibase.datasources.default.liquibase-schema=company

jpa.default.entity-scan.packages=ru.company.domain
jpa.default.properties.hibernate.hbm2ddl.auto=validate
jpa.default.properties.hibernate.default_schema=company

micronaut.metrics.enabled=true
micronaut.metrics.binders.web.enabled=true
micronaut.metrics.export.prometheus.enabled=true
micronaut.metrics.export.prometheus.step=PT15S

endpoints.prometheus.enabled=true
endpoints.prometheus.sensitive=false
