micronaut.application.name=company

datasources.default.url=${DB_URL:jdbc:postgresql://localhost:5432/postgres}
datasources.default.driver-class-name=org.postgresql.Driver
datasources.default.username=${DB_USERNAME:postgres}
datasources.default.password=${DB_PASSWORD:postgres}
datasources.default.dialect=POSTGRES

jpa.default.entity-scan.packages=ru.company.domain
jpa.default.properties.hibernate.hbm2ddl.auto=update
jpa.default.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
